{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "edge-app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.certManagerIssuer | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.annotations.forceSSLRedirect | quote }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "edge-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
