FROM docker.io/arm64v8/ubuntu:devel

ARG ARCH=arm64

ENV KUBERNETES_VERSION=v1.35
ENV TFVERSION=1.13.5

RUN id -u ${USER_ID} 2>/dev/null && userdel -f $(id -u ${USER_ID} -n) || echo "NO USER=${USER_ID}"
RUN getent group ${GROUP_ID} 2>/dev/null || groupadd -g ${GROUP_ID} ${GROUP_NAME}
RUN useradd -o -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash ${USER_NAME}
RUN test "${HOME}" = "/home/${USER_NAME}" || (mkdir -p $(dirname ${HOME}) && ln -s /home/${USER} "$(dirname ${HOME})/${USER_NAME}")

RUN apt update && apt install jq curl sudo openssh-client gpg -y
RUN curl -s -k https://api.github.com/repos/tfversion/tfversion/releases/latest | \
    jq -r '.assets[] | select(.name? | match("tfversion_.*linux_" + "${ARCH}")) | .browser_download_url' | xargs curl -s -k -L  | tar -C /usr/local/bin -zx tfversion

RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | sudo bash
RUN curl -s https://fluxcd.io/install.sh | sudo bash
RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
RUN apt update && apt install kubectl
USER ${USER_NAME}
RUN tfversion install ${TFVERSION} && tfversion use ${TFVERSION}
ENV PATH="/home/${USER}/.tfversion/bin:_var_PATH:/home/${USER}/bin"
WORKDIR /podman
