#!/bin/bash

podman run --rm -v ~/bin:/home/${USER}/bin \
  --user=$(id -u):$(id -g) --userns=keep-id \
  -v ~/.ssh:/home/${USER}/.ssh:U \
  -v ~/.kube:/home/${USER}/.kube:U \
  -v ${PWD}:/podman \
  -w /podman ic-podman-runtime:latest "$@"
