#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  HELM_CONFIG="$HOME/Library/Preferences/helm"
  HELM_CACHE="$HOME/Library/Caches/helm"
else
  HELM_CONFIG="$HOME/.config/helm"
  HELM_CACHE="$HOME/.cache/helm"
fi

mkdir -p "$HELM_CONFIG"
mkdir -p "$HELM_CACHE"
mkdir -p "$HELM_CONFIG/repository"
mkdir -p "$HELM_CACHE/repository"
mkdir -p "$HOME/.kube"

podman run --rm -it \
  --user=$(id -u):$(id -g) --userns=keep-id \
  -e "AWS_PROFILE=${AWS_PROFILE}" \
  -e "KUBECONFIG=${KUBECONFIG}" \
  -v "${PWD}:/podman" \
  -v "$HOME/.aws:/home/${USER}/.aws:U" \
  -v "$HOME/.kube:/home/${USER}/.kube:U" \
  -v "$HELM_CONFIG:/home/${USER}/.config/helm:U" \
  -v "$HELM_CACHE:/home/${USER}/.cache/helm:U" \
  ic-podman-runtime:latest helm "$@"
