#!/bin/bash

podman run --rm -v ~/bin:/home/${USER}/bin \
  --user=$(id -u):$(id -g) --userns=keep-id \
  -e "AWS_PROFILE=${AWS_PROFILE}" \
  -e "KUBECONFIG=${KUBECONFIG}" \
  -v "$HOME/.ssh:/home/${USER}/.ssh:U" \
  -v "$HOME/.kube:/home/${USER}/.kube:U" \
  -v "$HOME/.aws:/home/${USER}/.aws:U" \
  -v "${PWD}:/podman" \
  -w /podman ic-podman-runtime:latest "$@"
