#!/bin/bash

podman run --rm -it -v ${PWD}:/podman \
 --user=$(id -u):$(id -g) --userns=keep-id \
 -e "KUBECONFIG=${KUBECONFIG}" \
 -v ~/.aws:/home/${USER}/.aws:U \
 -v ~/.kube:/home/${USER}/.kube:U \
 ic-podman-runtime:latest kubectl "$@"
