#!/bin/bash

podman run --rm -it \
  --user=$(id -u):$(id -g) --userns=keep-id \
  -v "${PWD}:/podman" \
  -e "KUBECONFIG=${KUBECONFIG}" \
  -v "$HOME/.aws:/home/${USER}/.aws:U" \
  -v "$HOME/.kube:/home/${USER}/.kube:U" \
  ic-podman-runtime:latest flux "$@"
