FROM docker.io/amd64/ubuntu:devel

ARG ARCH=amd64

ENV ANSIBLE_VERSION=2.15.13
ENV ANSIBLE_RUNNER_VERSION=2.4.0
ENV VIRTUAL_ENV=/ic/ansible

RUN apt update && apt install -y python3 python3-pip python3-full software-properties-common
RUN mkdir -p ${VIRTUAL_ENV}
RUN python3 -m venv ${VIRTUAL_ENV} && . ${VIRTUAL_ENV}/bin/activate && \ 
    python3 -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org ansible-core==${ANSIBLE_VERSION} ansible-runner==${ANSIBLE_RUNNER_VERSION} jmespath urllib3 Jinja2 && \
    ansible-galaxy collection install ansible.posix community.general community.docker kubernetes.core amazon.aws

ENV PATH="$VIRTUAL_ENV/bin:$PATH"
WORKDIR /podman
