FROM docker.io/arm64v8/ubuntu:devel

ARG ARCH=arm64

ENV ANSIBLE_VERSION=2.15.13
ENV ANSIBLE_RUNNER_VERSION=2.4.0
ENV KUBERNETES_VERSION=v1.32
ENV TFVERSION=1.13.5
ENV VIRTUAL_ENV=/ic/ansible

RUN apt update && apt install -y python3 python3-pip python3-full software-properties-common jq curl sudo openssh-client gpg
RUN curl -s -k https://api.github.com/repos/tfversion/tfversion/releases/latest | \
    jq -r --arg ARCH "${ARCH}" '.assets[] | select(.name? | match("tfversion_.*linux_" + $ARCH)) | .browser_download_url' | xargs curl -s -k -L  | tar -C /usr/local/bin -zx tfversion
RUN tfversion install ${TFVERSION} && tfversion use ${TFVERSION}

ENV PATH="/root/.tfversion/bin:${PATH}"

RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
RUN apt update && apt install kubectl -y
RUN mkdir -p ${VIRTUAL_ENV}
RUN python3 -m venv ${VIRTUAL_ENV} && . ${VIRTUAL_ENV}/bin/activate && \ 
    python3 -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org ansible-core==${ANSIBLE_VERSION} ansible-runner==${ANSIBLE_RUNNER_VERSION} jmespath urllib3 Jinja2 && \
    ansible-galaxy collection install ansible.posix community.general community.docker kubernetes.core amazon.aws

ENV PATH="$VIRTUAL_ENV/bin:$PATH"
WORKDIR /podman
