#!/bin/bash

set -o nounset -o pipefail -o errexit

set -o allexport
ansible_ENV=$(dirname "$0")/.ansible/env
[[ -f ${ansible_ENV} ]] && source "${ansible_ENV}"
set +o allexport

exec podman run --rm -v ${PWD}:/podman \
  --user=$(id -u):$(id -g) --userns=keep-id \
  -v ~/.ssh:/home/${USER}/.ssh:U -e 'ANSIBLE_FORCE_COLOR=true' \
  localhost/ic-podman-ansible \
  ansible-playbook "$@"
